main_database:
    host: ""
    port: ""
    user: ""
    password: ""
    database: ""
access_database:
    host: ""
    port: ""
    user: ""
    password: ""
    database: ""
nickname_prefix: "~"
default_prefix: "&7"
patreon_prefix: "&6"
mod_prefix: "&4M &7"
cmod_prefix: "&4CM &7"
admin_prefix: "&4A &b"